### ISSUE TITLE
Number of apps in the same repository?

### ISSUE THREAD

**Issue by med1104** [RamiKrispin/shinyelive#4]
Hello, is it possible to have more than one shiny application on the same Github Page?

**Comment by RamiKrispin** [comment]
I did not try, but I believe you can, by customizing your `index.html` to call multiple pages, for example:

``` HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Business website</title>
  </head>
  <body>
    <nav>
      <a href="./index.html">Home</a>
      <a href="./app1.html">App 1</a>
      <a href="./app2.html">App 2</a>
      <a href="./app3.html">App 3t</a>
    </nav>
  </body>
</html>
```


You will have to render each app to the name you use in the `index.html` file above (e.g., `app1.index`, `app2.index`, etc.). You may need to set each app inside a subfolder to facilitate the additional files the app created during the render time.

**Comment by med1104** [comment]
Hi,

I finally finished this project. I was able to do it. I created my two apps, each in its directory. Then I executed:

```
shinylive export app1 docs --subdir app1
shinylive export app2 docs --subdir app2
```

Finally I created an `index.html` file with the following content:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Business website</title>
  </head>
  <body>
    <nav>
      <a href="./aap1/index.html">App 1</a>
      <a href="./aap2/index.html">App 2</a>
    </nav>
  </body>
</html>
```

Thank you for the `index.html` file model, I'm not good at HTML code so it helped me a lot.
